apiVersion: v1
kind: Service
metadata:
  name: nifi-frontend
spec:
  selector:
    app: nifi
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-frontend
spec:
  selector:
    matchLabels:
      app: nifi
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: nifi
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "whshk/nifi-frontend:latest"
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
